name: Express.js CI
on:
  push:
    branches: [ main ]

jobs:
  linting:
    name: Linting of the code
    run-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm i   
      - name: Run linting
        run: npm run lint
